name: umami-env

channels:
  - conda-forge

dependencies:
  - python=3.13
  - rdkit
  - numpy
  - pandas
  - openpyxl
  - scikit-learn
  - joblib
  - pip
  - pip:
      - streamlit==1.40.1

